# ServiceAccount
{{- if eq (include "archivist.serviceAccount.create" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archivist.serviceAccountName" . }}
  labels:
    {{- include "archivist.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

# RoleBinding
{{- if eq (include "archivist.serviceAccount.rbac.create" .) "true" -}}
{{- if .Values.serviceAccount.rbac.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "archivist.initEnv.role.name" . }}
  labels:
    {{- include "archivist.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "archivist.initEnv.role.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "archivist.initEnv.serviceAccountName" . }}

# Role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "archivist.initEnv.role.name" . }}
  labels:
    {{- include "archivist.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.serviceAccount.rbac.rules | indent 0 }}
{{- end }}

# ClusterRole
{{- if .Values.serviceAccount.rbac.clusterRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "archivist.clusterRole.name" . }}
  labels:
    {{- include "archivist.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.serviceAccount.rbac.clusterRules | indent 0 }}

# ClusterRoleBinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "archivist.clusterRole.name" . }}
  labels:
    {{- include "archivist.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "archivist.clusterRole.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "archivist.serviceAccountName" . }}
  namespace: {{ include "archivist.namespace" . }}
{{- end }}
{{- end }}
{{- end }}
