apiVersion: v2
name: archivist
description: Archivist is a decentralized durability engine that allows persisting data in p2p networks
type: application

keywords:
  - archivist
  - decentralized
  - durability
  - storage
  - p2p

home: https://archivist.storage

sources:
  - https://github.com/durability-labs/helm-charts/treen/main/charts
  - https://github.com/durability-labs/archivist-node/

# https://artifacthub.io/docs/topics/annotations/helm/
annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: Apache-2.0 MIT

maintainers:
  - name: Archivist DevOps
    email: devops@archivist.storage
    url: https://archivist.storage

icon: https://avatars.githubusercontent.com/u/219901300?s=400&u=ddf818a5eec7acfd2ede14e6a61d20c662aa52f4

version: 0.0.1
appVersion: 0.0.1
